version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: mwv2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mangwale_booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    container_name: mwv2-nats
    command: ["-js"]
    ports:
      - "4222:4222"

volumes:
  pgdata:
