http:
  routers:
    erp-redirect:
      rule: Host(`erp.sarvin.in`)
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: noop@internal
    erp-frontend:
      rule: Host(`erp.sarvin.in`) && PathPrefix(`/`)
      entryPoints: [websecure]
      tls: {}
      service: erp-frontend
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    erp-frontend:
      loadBalancer:
        servers:
          - url: http://172.17.0.1:8080
