version: "3.9"
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080" # dashboard on 8888 (auth recommended in prod)
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  spa:
    image: nginx:stable-alpine
    container_name: spa
    restart: unless-stopped
    volumes:
      - ../../apps/web-user/dist:/usr/share/nginx/html/user:ro
      - ../../apps/web-vendor/dist:/usr/share/nginx/html/vendor:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
volumes:
  letsencrypt:
